import { Component } from 'react'
import PopularCountryTabsItem from '../PopularCountryTabsItem'
import './index.css'
import PopularCityViewItem from '../PopularCityViewItem'


const PopularCountryTabsList=[
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/flag-uk.svg",
        countryName:"United States"
    },
    {
        id:2,
        img:"https://prod-static-assets.amberstudent.com/images/flag-aus.svg",
        countryName:"Australia"
    },
    {
        id:3,
        img:"https://prod-static-assets.amberstudent.com/images/flag-ire.svg",
        countryName:"Ireland"
    },
    {
        id:4,
        img:"https://prod-static-assets.amberstudent.com/images/flag-us.svg",
        countryName:"USA"
    },
    {
        id:5,
        img:"https://prod-static-assets.amberstudent.com/images/flag-can.svg",
        countryName:"Canada"
    },
    {
        id:6,
        img:"https://prod-static-assets.amberstudent.com/images/flag-ger.svg",
        countryName:"Germany"
    },
    {
        id:7,
        img:"https://prod-static-assets.amberstudent.com/images/flag-esp.svg",
        countryName:"Spain"
    }
]

const PopularCityViewList=[
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:6,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:7,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:6,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:7,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:6,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:3,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:2,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:7,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:7,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:7,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:5,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:5,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:1,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
    {
        id:1,
        img:"https://prod-static-assets.amberstudent.com/images/popular-cities/London/London_2.jpg?w=250&h=250&fit=crop&auto=format&trim=auto&q=10&fm=pjpg",
        countryTabId:4,
        cityName:"London"
    },
]

class PopularCity extends Component{
    state={
        selectedTabId:PopularCountryTabsList[0].id
    }

    selectTab=(id)=>{
        this.setState({
            selectedTabId:PopularCountryTabsList.filter(eachCountry=>eachCountry.id===id)[0].id
        })
    }
    
    render(){
        const {selectedTabId}=this.state
        console.log({selectedTabId})

        // Here Cities get filtered based on the Selected Country Tab  
        const filteredCities=PopularCityViewList.filter(eachCity=>eachCity.countryTabId===selectedTabId)
        
        return(
    <div className='popular-city-main-bg'>
        <h1>Popular Cities Across the Globe</h1>
        <p>Book student accommodations near top cities and universities around the world</p>
        <ul className='tabs-list'>
            {PopularCountryTabsList.map(eachCountry=>(
                <PopularCountryTabsItem isTabSelected={selectedTabId===eachCountry.id} selectTab={this.selectTab} key={eachCountry.id} eachCountry={eachCountry}/>
            ))}
        </ul>
        <ul className='views-list'>
            {filteredCities.map(eachCity=>(
                <PopularCityViewItem key={eachCity.id} eachCity={eachCity}/>
            ))}
        </ul>
        <button type='button' className='all-cities-btn'>View All Cities</button>
    </div>
)
        }
    }

export default PopularCity